Fixed size and position for the legend
replot/replot-map pull request #23
Opened 2017-11-16 22:49 UTC by alisaono

Fixed the legend so it no longer gets scaled/translated with the map when we're scaling on the map. 

![screen shot 2017-11-16 at 5 40 30 pm](https://user-images.githubusercontent.com/25045998/32920011-bb6c6208-caf5-11e7-9f81-2d5e43999313.png)
![screen shot 2017-11-16 at 5 40 42 pm](https://user-images.githubusercontent.com/25045998/32920012-bc15c208-caf5-11e7-9160-f8ff5f9978a2.png)

@AlmahaAlmalki @sanjaypojo #12 

Also my other concern with the current legend is, the legend overlaps the map. Luckily the legend ends up on the emptier part of the map right now, so it looks pretty nice, but if the legend ends up on some region, might be hard to see the legend? (Especially if the legend color happens to be the same as that region's color...!)

Two solutions I'm thinking of is to either move it outside and below the map or add white background to the legend. Let me know what you think!

2017-11-27 19:36 UTC, sanjaypojo commented
Hi @alisaono this looks great. Sorry, I thought I'd replied to this. I feel we could add a translucent background to the legend and also make it a little smaller. If you think that works, maybe you could just modify this PR with the changes?

2017-12-01 20:07 UTC, alisaono commented
@sanjaypojo @AlmahaAlmalki 
I made the legend a little smaller. I'm wondering if it's better to have a dark or light translucent background.

You can compare the samples with light background (dark text):
![screen shot 2017-12-01 at 2 48 59 pm](https://user-images.githubusercontent.com/25045998/33501011-f907074e-d6a8-11e7-9f26-3de94f6b2c54.png)
![screen shot 2017-12-01 at 3 02 39 pm](https://user-images.githubusercontent.com/25045998/33501027-09bcb1f6-d6a9-11e7-9e74-b2da79e42434.png)

with dark background (light text):
![screen shot 2017-12-01 at 3 01 36 pm](https://user-images.githubusercontent.com/25045998/33501044-1bc7239a-d6a9-11e7-838f-f0b7196f709a.png)
![screen shot 2017-12-01 at 3 03 09 pm](https://user-images.githubusercontent.com/25045998/33501046-1ca1734c-d6a9-11e7-970f-99de4500d327.png)

I think light background looks nice, but dark background has better readability...? What do you think?

2017-12-04 23:30 UTC, alisaono commented
@sanjaypojo 
Made the change so that the background (light/dark) is picked based on the darkness of color range.

If at least one color is light, pick dark background:
![screen shot 2017-12-04 at 6 21 56 pm](https://user-images.githubusercontent.com/25045998/33581981-033c3e9e-d921-11e7-8e54-f26db6b324fa.png)
Otherwise, light background:
![screen shot 2017-12-04 at 6 23 49 pm](https://user-images.githubusercontent.com/25045998/33581986-066b3264-d921-11e7-9f6f-26191c2fc810.png)
Also if one color is light and the other color is dark, just pick light background:
![screen shot 2017-12-04 at 6 22 43 pm](https://user-images.githubusercontent.com/25045998/33581978-020ebcae-d921-11e7-9207-b1b881fed8e5.png)

2017-12-07 17:11 UTC, sanjaypojo requested changes
Looks great apart from the one change (using `const` instead of `let`)

2017-12-07 17:11 UTC, sanjaypojo commented on src/Region.jsx
> +    let HEIGHT = 15
Maybe we can use `const` for the capitalized constants

2017-12-08 02:19 UTC, alisaono commented
@sanjaypojo Sounds good. Just changed them to consts!

2017-12-11 20:34 UTC, sanjaypojo approved these changes
Awesome stuff @alisaono 💯

2017-12-11 20:35 UTC, merged